### ISSUE TITLE
To-do till 1.0

### ISSUE THREAD

**Issue by Cludch** [Cludch/Node-JC3MP-Voicechat#1]
* document and clean up `client.ts`
* test
* get socket host and port from the server
* Gain and Send key configurable
* add settings to the `package.json` ain't work w/o
* add several events
* check if the voice chat is loaded too early. Should be loaded after the Player has been loaded. And how does it act on a respawn? (Network id etc. will break on respawn)
* add socket disconnect on voicechat disable

* add automatic releases (travis ci builds) for master merges (master will be protected later)
* performance measurements (maybe statsd compatibility)

**Comment by Rukenshia** [comment]
should probably create separate issues and add a milestone. I'm happy to contribute, but the issues should have proper description as to the desired behavior and more general information than a single bullet point.

**Comment by Cludch** [comment]
Will do. This was mostly just my personal to-do list.
