### ISSUE TITLE
don't send *.ts files to the client

### ISSUE THREAD

**Issue by Rukenshia** [Cludch/Node-JC3MP-Voicechat#2]
the jc3mp server ignores all files or directories starting with a dot or the hidden attribute on windows. since there is no use to have a `.ts` file on the client, I'd suggest either renaming it to `.client.ts` (transpiling to client.js) or move all `*.ts` files on the client (if there will ever be more than one) into a `.src` directory.

**Comment by Cludch** [comment]
This would cause redundant traffic.
I will either rename the files or move them to a different directory and create the package using Grunt then. If I decide to use Grunt, I might directly hardcode the socket ip + port.
